site_name: Ilot Invest Bali
slogan: INVEST IN BALI, INDONESIA
address: Jl. Raya Kerobokan 62, Kerobokan 80361 Bali
phone: (+62) 82144122029
author: Fabrice Giraud
instagram_url: https://www.instagram.com/ilotpropertybali/
facebook_url: https://www.facebook.com/ilotpropertybaliofficial/
main_website_url: https://ilotinvest.com/
google_analytics_tracking_id: G-EZ4NPR5HG6
about_text: >-
  Ilot Property Bali is composed of four distinct entities with expertise in
  Architecture, Construction, Development and Management.


  Today, we hold a substantial portfolio of completed luxury villas located in prime locations in Bali – driven by an unmatched commitment to quality and construction efficiency.
