site_name: Ilot Invest Bali
slogan: PROPERTY INVESTMENT IN BALI, INDONESIA
address: Jl. Petitenget No.882, Kerobokan Kelod, Kec. Kuta Utara, Kabupaten
  Badung, Bali 80361
phone: (+62) 819 1610 1970
author: Fabrice Giraud
instagram_url: https://www.instagram.com/ilotpropertybali/
facebook_url: https://www.facebook.com/ilotpropertybaliofficial/
main_website_url: https://ilotinvest.com/
google_analytics_tracking_id: G-EZ4NPR5HG6
about_text: >-
  **Q﻿uality First**


  We are the no 1 developer in Bali that promotes a conscious way to build & invest.


  O﻿ur development projects are located in premium areas to deliver the highest ROI.


  We respect the highest standard of construction ensuring the quality and integrity in all of our projects.
